name: Metadata

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]


jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2
