name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Lint
    permissions:
      contents: read # Allows reading the repo contents

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@0cfdcaa2dbe7a539dec471edbb081c88b06fe8ec # v1.24.2
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install lint deps
        run: |
          uds run lint:deps

      - name: Lint the repository
        run: |
          uds run lint:yaml
