name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Lint
    permissions:
      contents: read # Allows reading the repo contents

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install lint deps
        run: |
          uds run lint:deps

      - name: Lint the repository
        run: |
          uds run lint:yaml
