name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.bundle }} ${{ matrix.flavor }}
    runs-on: uds-swf-ubuntu-big-boy-16-core
    timeout-minutes: 40
    strategy:
      matrix:
        flavor: [upstream]
        type: [install, upgrade]
        bundle: ["k3d-demo", "dev"]
        exclude:
          - bundle: k3d-demo
            type: upgrade
            flavor: upstream
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}
          options: "--set BUNDLE_PATH=bundles/${{ matrix.bundle }}"

      - name: Debug Output
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@c52077c870a576d01f169f96d74d1b393c6488ba # v1.1.2
        with:
          suffix: ${{ matrix.type }}-${{ matrix.bundle }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
